spring:
  data:
    mongodb:
      username: lawal
      password: lawal
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090
  servlet:
    context-path: /api/v1

springdoc:
  default-produces-media-type: application/json
