spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/order
    username: LAWAL
    password: LAWAL
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-server: localhost:9092
      key-serializer: org.apache.kafka.common.serializer.StringSerializer
      value-serializer: org.springframework.kafka.support..serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.lawal.ecommerce.kafka.OrderConfirmation



server:
  port: 8070
  servlet:
    context-path: /api/v1

springdoc:
  default-produces-media-type: application/json

application:
  config:
    costumer-url: http://localhost:8222/api/v1/customer
    product-url: http://localhost:8222/api/v1/product
    payment-url: http://localhost:8222/api/v1/payment