spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/payment
    username: LAWAL
    password: LAWAL
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-server: localhost:9092
      key-serializer: org.apache.kafka.common.serializer.StringSerializer
      value-serializer: org.springframework.kafka.support..serializer.JsonSerializer
      properties:
        spring.json.type.mapping: PaymentNotificationRequest:com.lawal.ecommerce.notification.PaymentNotificationRequest


server:
  port: 8040
  servlet:
    context-path: /api/v1

springdoc:
  default-produces-media-type: application/json
